version: "3"

services:
  djangotest:
    build: ./myDjango04
    networks: 
      - composenet01
    restart: always

  nginxtest:
    build: ./myNginx04
    networks:
      - composenet01
    depends_on:
      - djangotest
    ports:
      - "80:80"
    restart: always

networks:
  composenet01:
